services:
  arti:
    image: hwangbyounghyeon/fastapi:latest
    container_name: fastapi
    volumes:
      - /home/ubuntu/artwork:/artwork/images
    networks:
      - arti

networks:
  arti:
    external: true
