FROM python:3.10.6

COPY ./requirements.txt /src/requirements.txt

COPY ./src /src

WORKDIR /src

RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0,0,0,0" , "--port", "80"]