services:
  arti:
    image: alsgml1532/arti:latest
    container_name: arti
    volumes:
      - /home/ubuntu/artwork:/var/images
    ports:
      - 5000:5000
    networks:
      - arti

networks:
  arti:
    external: true
